source "https://rubygems.org"

gem 'github-pages', '>= 224', group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", ">= 0.16.0"
  gem "jekyll-paginate"
  gem "jekyll-remote-theme", ">= 0.4.3"
  gem "jekyll-include-cache"
  gem "minimal-mistakes-jekyll", ">= 4.21.0"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data", ">= 1.2020.4"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?
